import esbuild from "esbuild";
import { readFileSync } from "node:fs";
import process from "process";
import { builtinModules } from "node:module";
import { config } from "dotenv";

config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const pluginConfig = JSON.parse(readFileSync(new URL("./plugin.config.json", import.meta.url), "utf8"));
const webAppUrl =
	process.env.STRATUM_WEB_APP_URL ?? pluginConfig.webAppUrl;
const supabaseUrl =
	process.env.STRATUM_SUPABASE_URL ?? pluginConfig.supabaseUrl;
const supabasePublishableKey =
	process.env.STRATUM_SUPABASE_PUBLISHABLE_KEY ??
	pluginConfig.supabasePublishableKey;
const apiBaseUrl = `${supabaseUrl.replace(/\/$/, "")}/functions/v1`;
const debugLogging = process.env.STRATUM_DEBUG === "true";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		__STRATUM_WEB_APP_URL__: JSON.stringify(webAppUrl),
		__STRATUM_SUPABASE_URL__: JSON.stringify(supabaseUrl),
		__STRATUM_SUPABASE_PUBLISHABLE_KEY__: JSON.stringify(supabasePublishableKey),
		__STRATUM_API_BASE_URL__: JSON.stringify(apiBaseUrl),
		__STRATUM_DEBUG__: JSON.stringify(debugLogging),
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
